theme = "varua"

[editor]
line-number = "relative"
cursorline = true
completion-timeout = 5
true-color = true
rulers = [80]
bufferline = "always"
trim-trailing-whitespace = true
insert-final-newline = true

[editor.indent-guides]
render = true
