theme = "base16_transparent"

[editor]
line-number = "relative"
cursorline = true
true-color = true
rulers = [80]
bufferline = "always"

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = false
