Section "InputClass"
	Identifier "touchpad"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "Tapping" "on"
	Option "NaturalScrolling" "true"
	Option "Scrolling Pixel Distance" "10"
	Option "Accel Speed" "0.25"
EndSection
